import os
import subprocess
import glob
from shutil import move
from astropy.io import fits
import progressbar


def perform_astrometry(target, dirtarget, filters, verbose=False):
    """Adds accurate WCS information to all headers in dataset.

    Finds coordinates of stars using imstar command and WCS information
    generated by astrometry.net and writes information to a table called
    new-image.tab. It then adds the WCS information from new-image.fits to the
    headers of all the images in the dataset to get a preliminary estimate of
    the true WCS information. It writes these files and then uses imstar to
    correct the WCS information in each header. These files are copeied to a
    new directory withtin WCS called accurate_WCS.

    Parameters
    ----------
    target : str
        Name of target.
    dirtarget : str
        Directory containing all bias, flat, and raw science images.
    filters : list
        List containing string of each filter keyword found in header of flat
        field and light frame images.
    verbose : boolean, optional
        Print information about status of program.

    Returns
    -------
    None
    """
    os.chdir(dirtarget)

    # Creates new-images.tab file with positions of stars.
    args = '-vhi' if verbose else '-hi'
    subprocess.call(['imstar', args, '700', '-tw', 'new-image.fits'])

    # Gets header with WCS information to append to all images.
    wcsim_hdu = fits.open(os.path.join(dirtarget, 'new-image.fits'))
    wcsim_header = wcsim_hdu[0].header

    # Repeats process for images of each filter.
    for fil in filters:
        os.mkdir(os.path.join(dirtarget, fil, 'WCS'))

        # Creates progress bar object to show status to user.
        widgets = [progressbar.Bar('=', '[', ']'), ' ',
                   progressbar.Percentage(), ' ', progressbar.ETA()]

        # Reads in all target files.
        if verbose:
            progress = progressbar.ProgressBar(widgets=widgets)
            images = progress(glob.glob(os.path.join(dirtarget, fil,
                                                     '*.fits')))
        else:
            images = glob.glob(os.path.join(dirtarget, fil, '*.fits'))

        for n, image in enumerate(images):
            other_hdu = fits.open(image)
            imagedata = other_hdu[0].data
            other_header = other_hdu[0].header

            # Finds all uncommon header keywords.
            diff = fits.HeaderDiff(wcsim_header, other_header).diff_keywords[0]

            for keyword in diff:
                # Skips unneeded header keywords and adds uncommon keywords
                # and their value to images.
                if keyword not in ('COMMENT', 'HISTORY'):
                    other_header.set(keyword, wcsim_header[keyword])

            # Writes file.
            hdu = fits.PrimaryHDU(imagedata, header=other_header)
            hdulist = fits.HDUList([hdu])
            out_path = os.path.join(dirtarget, fil, 'WCS', target + '_' +
                                    fil + '_{}.fits'.format(n))
            hdulist.writeto(out_path, overwrite=True)

        # Moves new-image.tab to WCS folder so that it may be used by imwcs.
        move('new-image.tab', os.path.join(fil, 'WCS'))
        # Corrects WCS information in image header using the imwcs command and
        # known star coordinates in new-image.tab.
        os.chdir(os.path.join(dirtarget, fil, 'WCS'))
        isr_wcs_images = glob.glob(os.path.join(dirtarget, fil, 'WCS',
                                                '*.fits'))
        for i, image in enumerate(isr_wcs_images):
            if verbose:
                subprocess.call(['imwcs', '-wv', '-i', '100', '-c',
                                 'new-image.tab', target + '_' + fil +
                                 '_{}.fits'.format(i)])
            else:
                subprocess.call(['imwcs', '-w', '-i', '100', '-c',
                                 'new-image.tab', target + '_' + fil +
                                 '_{}.fits'.format(i)])
        # Moves corrected images to separate directory.
        isr_wcs_images = glob.glob(os.path.join(dirtarget, fil, 'WCS',
                                                '*w.fits'))
        os.mkdir(os.path.join(dirtarget, fil, 'WCS', 'accurate_WCS'))
        out_path = os.path.join(dirtarget, fil, 'WCS', 'accurate_WCS')
        for image in isr_wcs_images:
            move(image, out_path)
